### ISSUE TITLE
The events in the example are not recognized by homeassistant

### ISSUE THREAD

**Issue by ysqspdk** [Chreece/BTHomeV2-ESP32-example#21]
![image](https://github.com/Chreece/BTHomeV2-ESP32-example/assets/26348364/48efeed3-d469-4809-b399-f65c54dd5179)

**Comment by countrysideboy** [comment]
1. Events will be supported in Home Assistant 2023.5 and higher.
2. You should listen the event of bthome_ble_event in the Developer Tools -- event menu.

**Comment by ysqspdk** [comment]
I don't quite understand, this is the service data of Bluetooth, including the battery, button A and button B. Is this service data correct?
`40 01 5A 3A 02 3A 00`

**Comment by ysqspdk** [comment]
I'm sorry. I get it
